spring:
  application:
    name: GATEWAY
  profiles:
    active: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      routes:
        - id: TRANSACTION-PROCESSOR
          uri: lb://TRANSACTION-PROCESSOR
          predicates:
            - Path=/transactions/**
          filters:
            - name: CircuitBreaker
              args:
                name: transactionProcessorCB
                fallbackUri: forward:/fallback/transaction-processor

management:
  endpoint:
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'