spring:
  application:
    name: GATEWAY
  profiles:
    active: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userServiceCB
                fallbackUri: forward:/fallback/user-service

management:
  endpoint:
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'