server:
  port: 9003

spring:
  application:
    name: TRANSACTION-PROCESSOR
  datasource:
    url: jdbc:mysql://${HOST_NAME:localhost}:${HOST_PORT:3306}/${MYSQL_DATABASE:smartosc?createDatabaseIfNotExist=true}
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      show-sql: true